version: '3.8'

services:
  redis-test:
    image: redis:7-alpine
    container_name: wind-redis-test
    ports:
      - "6380:6379"
    command: redis-server --requirepass windgame123
    volumes:
      - redis-test-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "windgame123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodb-test:
    image: mongo:7.0
    container_name: wind-mongodb-test
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--noauth"]
    volumes:
      - mongodb-test-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-test-data:
  mongodb-test-data: